package hashtable;

import java.util.Arrays;

public class FindTheDifference
{
  public static char findTheDifference(String s, String t)
  {
    // Use array instead of String object to get better for runtime.
    if (s.length() == 0) {
      return t.charAt(0);
    }
    
    char[] array = s.toCharArray();
    char[] arrayT = t.toCharArray();
    int[] map = new int[26];
    for (int i = 0; i < array.length; i++) {
      //map[s.charAt(i) - 'a']++;
      map[array[i] - 'a']++;
    }
    for (int i = 0; i < arrayT.length; i++) {
      //if (map[s.charAt(i) - 'a'] == 1) {
      if (map[arrayT[i] - 'a'] == 0) {
        //System.out.println("")
        return arrayT[i];
      } else {
        map[arrayT[i] - 'a']--;
      }
    }

    return array[0];
  }

  public static char findTheDifferenceOpt(String s, String t) 
  {
    char result = 0;
    for (char c : s.toCharArray()) {
        result ^= c;
    }
    for (char c : t.toCharArray()) {
        result ^= c;
    } 
    return result;
  }
  
  public static void readme()
  {
    String str = "You are given two strings s and t.\n\n";

    str += "String t is generated by random shuffling string s and then add one more letter at a random position.\n\n";

    str += "Return the letter that was added to t.";

    System.out.println(str);
  }

  public static void main() 
  {
    FindTheDifference.readme();

    // s = "abcd", t = "abcde" => 'e'
    String s = "abcd";
    String t = "abcde";
    System.out.println("findTheDifference(" + s + ", " + t + ") = " + 
                        findTheDifference(s, t));

    // s = "", t = "y" => 'y'
    s = "";
    t = "y";
    System.out.println("findTheDifference(" + s + ", " + t + ") = " + 
                        findTheDifference(s, t));

    System.out.println("findTheDifferenceOpt(" + s + ", " + t + ") = " + 
    findTheDifferenceOpt(s, t));

  }
}